# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'git@github.com:applicaster/CocoaPods.git'
source 'git@github.com:CocoaPods/Specs.git'
source 'git@github.com:applicaster/CocoaPods-Private.git'
source 'git@github.com:applicaster/PluginsBuilderCocoaPods.git'
source 'git@github.com:applicaster/applicaster-iap-framework'
source 'git@github.com:applicaster/applicaster-cam-framework'

target 'StarterKitPluginSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StarterKitPluginSample

  pod 'CAMStarterKit', :path => '../Content Access Plugins Starter Kit/CAMStarterKit.podspec'

end
